### ISSUE TITLE
One to One Relationship

### ISSUE THREAD

**Issue by Maast3r** [amberframework/granite#101]
There doesn't seem to be a way currently to have One to One relationship. For example, in Rails, there is:
Class A
has_a :class_b
end

Class B
belongs_to :class_a
end

What is the suggested workaround for now (if there is any)? Just use One to Many relationships to fake a One to One?

**Comment by drujensen** [comment]
@Maast3r yes, you can use a `has_many` as a work around.  

You can also add a method to return the first object:
```
Class A
  has_many :class_b
  
  def class_b
    class_bs.first
  end
end
```

Finally, you could write a `macro has_a` inside a `macro inherited` in your base model and then use that instead.

**Comment by Maast3r** [comment]
Thanks!
