### ISSUE TITLE
Support not nil and default values in mapping

### ISSUE THREAD

**Issue by drujensen** [amberframework/granite#115]
Look at supporting not nilable types in the mapping.  Also provide default values.  

This should modify the generation of the `property field : Type = default` macro generator with parameters provided in the mapping.

**Comment by robacarp** [comment]
Great! I was looking at the field macro yesterday thinking about how to add a default value

**Comment by robacarp** [comment]
@drujensen I did some similar work [here, on mosquito](https://github.com/robacarp/mosquito/blob/master/src/mosquito/queued_job.cr#L14-L34).

The syntax is notably different in the way parameters are generated:

```crystal
# Granite
param name : String
param age : Int64

# Mosquito
params(
  name : String,
  age : Int64
)
```

However this bit of code seems like it could be helpful for this:

```crystal
            type = nil
            simplified_type = nil
            contains_nil = nil

            if parameter.is_a? Assign
              name = parameter.target
              value = parameter.value
            elsif parameter.is_a? TypeDeclaration
              name = parameter.var
              value = parameter.value
              type = parameter.type
            else
              raise "Unable to generate for #{parameter}"
            end
```

**Comment by drujensen** [comment]
When I started building granite, I was following the [JSON.mapping()](https://crystal-lang.org/api/0.24.1/JSON.html#mapping%28_properties_%2Cstrict%3Dfalse%29-macro) syntax:
```
DB.mapping(
  name : {type: String, nilable: true}
  age : Int64
)
```

When they added the `finished` macro, I felt like the `param : String` was a better approach, but I'm open to moving back if it makes things easier.  It would require less macros and would follow the way mappings are done in crystal stdlib.

**Comment by robacarp** [comment]
Uh, I don't have a preference one way or another. I wasn't trying to suggest changing the DSL, I was just making a note of the fact that the crystal compiler provides a value getter on a TypeDeclaration.

That said, you mentioned the finished macro and that reminded me of this comment:

> I don't know, finished feels to me like a dirty hack, and also gathering stuff in compile-time constants. Plus it doesn't work well regarding the type of instance vars (they are not available in the finished hook). I think finished and general attributes need some thoughts first.

From: https://github.com/crystal-lang/crystal-book/issues/188

Granite has a lot of code that's generated by the `finished` hook, it might be worth following whatever discussion the crystal-lang group has on the subject.

**Comment by drujensen** [comment]
@robacarp Right.  I have been through the cycle where they added the `finished` macro thinking that this would be a really nice way to make mappings clean.  I went ahead and converted Granite to use it.  Then the conversation turned that maybe the `finished` macro is not so good of an idea after all.  It does seem kinda a hacky solution on the backend of it.  The user experience however is pretty nice.

Regarding the `TypeDeclaration`, I kinda assumed we would need to change the syntax.  In either case, I like your approach and it allows for multiple ways of declaring the mapping.  

I'm open to moving away from the `finished` macro.  I think it will clean up the backend code and I think the `DB.mapping` is not too much to ask.

@amberframework/granite-orm-contributors Would love to hear others opinion on the subject.

**Comment by eliasjpr** [comment]
I like the consistency of the `DB.mapping` resembles the `JSON.mapping`, but  I also like the idea of declaring the db mapping as such.

```
Db.schema :table_name do 
  field user_id : Int64,  { index: true }
  field email : String,  { index: true, size: 128, null: false }
  timestamps
end
```

Something like above opens a world of flexibility, where we can generate `migrations`  based on the DB.mapping definitions, if the mapping changes it generates a new migration altering the table. Something I used to enjoy a lot from Java Hibernate ORM and elixir . We can still keep migrations as is, not asking to change it, is just the possibilities that it opens up.

I like the `TypeDeclaration` approach a lot. 👍

**Comment by msa7** [comment]
I have to adds `phone_number!` and `phone_country_code!` to model for avoid `.not_nil!` elsewhere. Is there better way? Maybe Granit should generate `phone_number!` automatically? 

```
class DB::Verification < Granite::Base
  adapter pg
  table_name verifications

  # id : Int64 primary key is created for you
  field phone_country_code : Int32
  field phone_number : String
  timestamps

  def phone_number!
    phone_number.not_nil!
  end

  def phone_country_code!
    phone_country_code.not_nil!
  end
```

**Comment by Blacksmoke16** [comment]
You can add a `!` after field to tell Granite that that field should be not nil.  For example:
```Cr
class DB::Verification < Granite::Base
  adapter pg
  table_name verifications

  # id : Int64 primary key is created for you
  field! phone_country_code : Int32
  field! phone_number : String
  timestamps
end
```

**Comment by c910335** [comment]
@msa7 
Actually, the raise-on-nil methods you said are generated automatically since #171.
