### ISSUE TITLE
Fix pluralization issues with relationships

### ISSUE THREAD

**Issue by drujensen** [amberframework/granite#129]
Look into integration of an inflector: https://github.com/luckyframework/lucky_inflector

EDIT:
I think I agree with @shayneoneill that this is one feature in rails that creates a lot of pain.

I think a better solution is to default to singular but allow for overriding the name so:
```
belongs_to :user
has_many :car
```

This would use the `Car` class and default to `car_id`.   

If someone wanted to use the plural form:
```
belongs_to :user
has_many :cars, class_name: Car
```

You would be required to specify the class name.  We should also support the `foreign_key` to override the default.

**Comment by shayneoneill** [comment]
Is this something you really want? I always considered this an anti-feature in rails, an unneccesary form of magic that got in the way of readability and seemed to confuse ides

**Comment by drujensen** [comment]
@shayneoneill PR #278 removes the pluralization of the table name and the has_many relationship.  It always felt like a hack to me and removing it feels great!  Take a look at the PR and provide any feedback.  Thanks!

**Comment by shayneoneill** [comment]
perfect.
