### ISSUE TITLE
Support Custom Types

### ISSUE THREAD

**Issue by drujensen** [amberframework/granite#136]
Allow someone to provide a custom type.  Provide a mechanism to convert the type to/from the database type.

```
class Granite::ORM::CustomType
  abstract def to_db(value : T)
   #TODO: convert from the crystal type to the db type
  end
  abstract def from_db(value : T)
   #TODO: convert from the db type to the crystal type
  end
end
```

Check to see if the type is a custom type and call the appropriate methods during storage and retrieval from the db.

**Comment by eliasjpr** [comment]
Thought: Maybe this can be part of the field definition where you can specify the db type and the class type

**Comment by drujensen** [comment]
Yes, absolutely.

```
field address : Address
```

**Comment by Blacksmoke16** [comment]
Can we restart the discussion on this?  After setting up PG, i noticed we don't have support for the more advanced types it offers.  

How do we want this to work?
What will be involved?
Should this come with a refactor to the `cast_to_field` method?

**Comment by drujensen** [comment]
Yes. We should refactor the cast_to_fields and support duck typing or a type extension that will add a method that will cast its type correctly. This will remove the case statement and allow for other custom types.

**Comment by Blacksmoke16** [comment]
Cool, i have a few ideas about this but i'll see how it goes.

**Comment by Blacksmoke16** [comment]
Yea..i'm not too sure how to manage this.

I have a semi working version for NamedTuple args.  But the main issue points im having are like casting the unioned types of everything into what the var should be, and managing casting errors.

Any tips/ideas?  I'll keep thing as well..

**Comment by Blacksmoke16** [comment]
Little update.  Managed to get saving/reading PG array.

However i'm open for ideas on better ways to handle the casting.  Is my major blocker right now.

```Crystal
    disable_granite_docs? def set_attributes(args)
      {% for _name, options in FIELDS %}
        {% unless _name.stringify == PRIMARY[:name].stringify %}
          if at = args[:{{_name.id}}]?
            if cst = at.as?({{options[:type].id}})
              @{{_name.id}} = cst
            else
              # Need a way to cast ivar to correct Type if .as(Type) fails
              # For example giving an Int32 as String
            end
          end
        {% end %}
      {% end %}
    end
```

**Comment by drujensen** [comment]
I'm going to close this in favor of Adapter specific types issue #152

**Comment by eliasjpr** [comment]
By specifying both, we can do the casting or attempt to do the casting using Crystal `type.as(other_type)`, also it will allow us to create the DB table structure with specific DB types if the user wants more control over that. This is something that I have seen in Hibernate (Java ORM) and many other ORMs
