### ISSUE TITLE
Incorrect quoting, preventing Pg schema specification

### ISSUE THREAD

**Issue by docelic** [amberframework/granite#149]
In one of recent commits, quoted_table_name was introduced.

This breaks functionality if table name contains a Pg schema name like schemaname.tablename.

quoted_table_name() quotes both inside double quotes to produce "schemaname.tablename", while the proper way to quote is "schemaname"."tablename".

The source of the problem is probably this function:

```
diff --git a/src/adapter/base.cr b/src/adapter/base.cr
index e29e5c5..1a5958c 100644
--- a/src/adapter/base.cr
+++ b/src/adapter/base.cr
@@ -60,6 +60,15 @@ abstract class Granite::Adapter::Base
     Granite::Adapter::Base.env(url)
   end
 
+  # Use macro in order to read a constant defined in each subclasses.
+  macro inherited
+    # quotes table and column names
+    def quote(name : String) : String
+      char = QUOTING_CHAR
+      char + name.gsub(char, "#{char}#{char}") + char
+    end
+  end
```

**Comment by docelic** [comment]
@maiha mentioning you here since it seems relevant.

**Comment by maiha** [comment]
Nice! It's a bug I've created. I'll create a PR soon.

**Comment by robacarp** [comment]
Since there's an open pull, I'm locking this issue to prevent forking the discussion. See #150 as referenced above by the github bots.

**Comment by drujensen** [comment]
@robacarp do you have a recommendation on how to address this issue?

**Comment by robacarp** [comment]
I can think of a couple things:

1. Provide a method called `quoted_table_name` which does the right thing for most use cases, but can be overridden in models if a developer is using a namespaced table
1. Provide a method called `quote_table_name` which simply looks for a period and divides the string if needed, then calls `quote` on the appropriate parts.
