### ISSUE TITLE
Support Adapter-specific types

### ISSUE THREAD

**Issue by maiha** [amberframework/granite#152]
Using DB-specific type

```crystal
class Batch < Granite::ORM::Base
  adapter mysql
  field start_time : Time::Span
```

causes

```
no overload matches 'Hash(String, Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil)#[]=' with types String, (Time::Span | Nil)
Overloads are:
 - Hash(K, V)#[]=(key : K, value : V)
Couldn't find overloads for these types:
 - Hash(String, Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil)#[]=(key : String, value : Time::Span)
```

#### status
- ✅ MySQL supports `time` type
- ✅ `mysql` shard supports `time` type as `Time::Span`
- ✅ `crystal-db` shard can handle any custom types.  (see [example](https://github.com/crystal-lang/crystal-db/blob/master/spec/custom_drivers_types_spec.cr#L97-L98))
- ❌ Granite supports only `DB::Any`

#### codes

Currently, we use `DB::Any` statically in `module Foo` like this.

```crystal
    def to_h
      fields = {} of String => DB::Any
```

I think that the correct solution is to rewrite this part by macro.
```diff
-      fields = {} of String => DB::Any
+      fields = {} of String => {{adapter}}::Any
```

I tried this a few hours, but I don't know how to pass `adapter` macro value into all other files.
Or, is it better to define modules as `Granite::ORM::Fields(T)` where `T` is one of adapters?

Thus, it was not easy to be solved. So I created an issue first. 😄

**Comment by robacarp** [comment]
Here's what I've been imagining.

Granite needs a bit of a refactor in the DSL, and I think @drujensen and I both want to land in a place like this:

```crystal
class Model < Granite::Model
  db.mapping do
    field column_name : Type
    field column2_name : Type
    field column3_name : Type
  end
end
```

I was musing the other night about how important it is for each part of this to be override-able. Custom data types are going to be added over time and in order for Granite not to be handicapping when someone wants to use something like Mysql Time Span, or Postgres GIS, it needs to provide custom data marshaling. I find myself imagining the above DSL with _a lot_ of override-able defaults. If each and every part of the process is override-able, it might look something like this:


```crystal
class Model < Granite::Model
  db.mapping do
    field(
      # Type? => can be nil
      # value => default value for initialized objects
      column_name : Type? = value,

      # accessor: to override default getter/setter names to allow for mapping
      accessor: :other_name,

      # marshal/demarshal: to override default type casting to send to and read from the database
      marshal: :type_marshal_method, demarshal: :type_demarshal_method,

      # serialization: to override serialization for use with json/yaml/xml/etc
      serializer: :type_serializer_method
    )

    # more fields:
    field name : String?
    field age : Int32?
    # etc...
  end
end
```

Most use cases would never need anything but the basic `field name : String? = 'user'` syntax, but custom data types, application specific overrides, etc can be created which allow a much deeper integration with the database.

**Comment by drujensen** [comment]
This is a much needed update.  @robacarp @maiha would either of you have time to work on this?

**Comment by maiha** [comment]
Yes, I am interested in this. However, I think that it will take a few months, and it will be a big change including the adapter. The specification I want is clear, but implementation requires many trial and error.

This is because implementations dealing with types often collide with Crystal language restrictions and barriers. In addition, there are cases in which the specification itself is changed due to language defects.

**Comment by drujensen** [comment]
this is similar to #136

**Comment by eliasjpr** [comment]
By specifying both class and db type we can do the casting or attempt to do the casting more explicitly, using Crystal type.as(other_type), also it will allow us to create the DB table structure with specific DB types if the user wants more control over that. This is something that I have seen in Hibernate (Java ORM) and many other ORMs

**Comment by drujensen** [comment]
We should be able to get the type via the definition of the field itself.  `field name : PG::Numeric?`  If we add support for custom types, then you could define your own field `field name : MyNumeric` that has the ability to handle the marshaling.

**Comment by Blacksmoke16** [comment]
Also know to actually declare your field as type `MyCustomType` there has to be a way to tell each db adapter shard how to handle that type.  Otherwise you would get errors like:

```
Unhandled exception: PG::ResultSet#read returned a String. A (UUID | Nil) was expected. (Exception)
```

Example for adding one of UUID for PG
```Crystal
struct UuidDecoder
  include PG::Decoders::Decoder

  def decode(io, bytesize)
    bytes = uninitialized UInt8[6]
    str = String.new(36) do |buffer|
      buffer[8] = buffer[13] = buffer[18] = buffer[23] = 45_u8

      slice = bytes.to_slice[0, 4]

      io.read(slice)
      slice.hexstring(buffer + 0)

      slice = bytes.to_slice[0, 2]

      io.read(slice)
      slice.hexstring(buffer + 9)

      io.read(slice)
      slice.hexstring(buffer + 14)

      io.read(slice)
      slice.hexstring(buffer + 19)

      slice = bytes.to_slice
      io.read(slice)
      slice.hexstring(buffer + 24)

      {36, 36}
    end
    UUID.new str
  end
end

PG::Decoders.register_decoder UuidDecoder.new, 2950
```
