### ISSUE TITLE
Ability to bulk import array of models

### ISSUE THREAD

**Issue by Blacksmoke16** [amberframework/granite#156]
# Use case:
Use from_json or from_yaml to produce an array of db models.  Currently (afaik) the only way to import them all is to iterate through the array and call `.save` on each model, which causes an INSERT statement to be executed for each record.

An `.import` or something similar method on the array would create a few transactions to bulk insert a few thousand records at a time.

See https://github.com/zdennis/activerecord-import as an example.

**Comment by Blacksmoke16** [comment]
A workaround until a better solution is implemented

```Crystal
class Array
  def import
    self.each_slice(2500) do |s|
      c = s.first.class
      stmt = "INSERT INTO #{c.to_s.downcase}s (#{c.fields.join(",")}) VALUES "
      s.each_with_index do |o, idx|
        stmt += "(#{o.values.join(",") { |i| %("#{i}") }})"
        stmt += "," if (s.size - 1) != idx
      end
      Name.exec stmt
    end
  end
end
```

Also need a `values` model method
```Crystal
  def values
    c = self.class
    keys = c.fields
    keys << c.primary_name unless c.primary_name == "id"
    keys.map { |k| self.to_h[k] }
  end
```

**Comment by robacarp** [comment]
@Blacksmoke16 aside from monkeypatching Array, this seems like it's worth fleshing out. The recently added [Adapter&quote](https://github.com/amberframework/granite-orm/blob/master/src/adapter/base.cr#L66-L69) method should help.

I think it's probably best to avoid doing any polymorphism and instead require the array to be single-model only, so that the table name isn't part of the data.

**Comment by Blacksmoke16** [comment]
For sure, this sped up importing for me from a good while to like 30sec.

I'll have to check that out.  Current issue i found with my quick monkeypatch is working with null values, it quotes them so it doesn't know what to do when going to run the INSERT.  Shouldn't be a major issue to fix.  Requiring the array to be of a single model would be fine.  Simple and effective to start off would be best.

But yea, a legit feature to do this would be great to have.

**Comment by Blacksmoke16** [comment]
I been messing with this for a bit wanted to see what your thoughts are on this in regards to the best way to implement it.

As of now, unless you guys have a better idea, I added a new class level method to the `Transactions` class, `self.import(models)`, that takes an array of models as a param.  It then constructs the initial `INSERT INTO TABLE_NAME (LIST_OF_FIELDS) VALUES ` then loops over the models array and adds a VALUES set for each model; skipping ones that are not valid as well as raising an exception if one model does not match the class import was called on (to prevent polymorphism importing as discussed above)

One of the main questions i have now is how the other methods in mysql.cr use `statement, params` where the statement contains the placeholders and params the values.  However i'm thinking that won't work with multiple VALUES sets, so would have to include the insert values directly into the statement.  

This brings the question of the best way to handle param escaping as well as making sure to quote string values with single quotes.

**Comment by elorest** [comment]
Usually this sort of mass import is better as "LOAD DATA IN FILE" with csv or just one big sequel statement. Not sure if this is something that should be part of the ORM or not.

**Comment by robacarp** [comment]
@blacksmoke16 your approach sounds fine to me. I would put a type filter on the import function to let crystal throw an error if the wrong model army was tried. 

As for your statement construction, I’m not sure. If you’re open to submitting a pull request, I’d be happy to take a look. 

As @elorest said, some people do huge imports by sql file, but I think there is room for this type of import as well. A bulk create api endpoint is a perfect example.

**Comment by Blacksmoke16** [comment]
Sure, i'll prob have a PR for this weekend.

**Comment by Blacksmoke16** [comment]
This can be marked as done now that #168 is merged.
