### ISSUE TITLE
Error with normal constructor with JSON.mapping

### ISSUE THREAD

**Issue by Blacksmoke16** [amberframework/granite#170]
Initializing a new Granite model using Model.new(args), with a JSON.mapping in the model does not work.

```Crystal
    class Item < Granite::ORM::Base
     JSON.mapping(
        type_id: Int32,
        type_name: String
     )

      adapter mysql
      primary type_id : Int32, auto: false
      field type_name : String
    end
```

Doing `Item.new(type_id: 1, type_name: "item1")` produces:

```
Error in src/api2.cr:20: missing argument: __temp_42
Overloads are:
 - Item.new(__temp_42 : ::JSON::PullParser)

p Item.new(type_id: 111, type_name: "Rhea")
                     ^~~
```

The error can be corrected by adding `def initialize(@type_id, @type_name) end` but that seems not ideal.

It would be even better if the defining of the fields/primary using granite notation would also allow for `Model.from_json` since they are basically the same definitions but in different formats.

**Comment by drujensen** [comment]
@Blacksmoke16 We added support for `to_h` and `to_json` so you wouldn't need to provide the mapping.  Does this satisfy your request or do you need the JSON mapping for other reasons?

https://github.com/amberframework/granite-orm/blob/master/src/granite_orm/fields.cr#L94

**Comment by Blacksmoke16** [comment]
Not quite.  I am referring to going the other way.  FROM a json string, TO a Granite model object.

**Comment by drujensen** [comment]
The constructor supports a Hash(String, JSON::Type) 

https://github.com/amberframework/granite-orm/blob/master/src/granite_orm/base.cr#L36

Can you try `Model.new(json.to_h)`?

**Comment by Blacksmoke16** [comment]
I can't seem to get the data into that format of a Hash.
```Crystal
try1 = {type_id: 1, type_name: "item1"}
try2 = {type_id: 1, type_name: "item1"}.to_h
try3 = {type_id: 1, type_name: "item1"}.to_json

p Item.new(try1)
p Item.new(try2)
p Item.new(JSON.parse(try3).to_h)
```
All seem to produce the `no overload matches...` 

Unless im missing how to get the NamedTuple/Hash/JSON whatever to that format...

**Comment by drujensen** [comment]
@Blacksmoke16 yeah, ok. I tried several things as well with no success. It's expecting `JSON::Any` which we should support to make API's easier to deal with.

**Comment by Blacksmoke16** [comment]
I did find a workaround for this.  Can define a json mapping and call `from_json` on your model as opposed to using new or create.

However native support of Model.create(json) would be pretty slick, espcially since the JSON mapping is pretty much a duplicate of the fields mapping.

item.cr
```Crystal
  class Item < Granite::ORM::Base
    JSON.mapping(
       type_id: Int32,
       type_name: String,
       price: Float64,
       published: Bool,
    )

    adapter mysql
    table_name items
    primary type_id : Int32, auto: false
    field type_name : String
    field price : Float64
    field published : Bool
  end
```

app.cr
```Crystal
  data = [] of Item
  data << Item.from_json(%({"type_name": "Item1", "price": 19.99, "type_id": 1, "published": true}))
  data << Item.from_json(%({"type_name": "Item2", "price": 0.00, "type_id": 2, "published": false}))
  data << Item.from_json(%({"type_name": "Item3", "price": 4.00, "type_id": 3, "published": true}))

  Item.import(data)
```
```
I, [2018-05-05 18:14:25 -04:00 #15016]  INFO -- Granite: INSERT INTO `items` (`type_id`, `type_name`, `price`, `published`) VALUES (?,?,?,?),(?,?,?,?),(?,?,?,?): [1, "Item1", 19.99, true, 2, "Item2", 0.0, false, 3, "Item3", 4.0, true]
```
