### ISSUE TITLE
/usr/bin/ld: cannot find -lyaml

### ISSUE THREAD

**Issue by girng** [amberframework/granite#178]
just followed tutorial

fresh installation
and added
```
require "granite_orm/adapter/mysql"

class Post < Granite::ORM::Base
  adapter mysql
  field name : String
  field body : String
  timestamps
end
```

to my project. and added config/database.yml and filled it out to my root directory.

but whenever i run my crystal app, i get: 

```
/usr/bin/ld: cannot find -lyaml
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/girng/.cache/crystal/crystal-run-MasterServer.tmp'  -rdynamic  -lyaml `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

what am i doingwrong? any idea? i'm on Windows 10 WSL btw

**Comment by girng** [comment]
# solution


From IRC (bridge bot)
@FromIRC
10:39
<oprypin> @girng, install libyaml-dev
<oprypin> @girng, https://github.com/crystal-lang/crystal/wiki/All-required-libraries#ubuntu


@oprypin, thank you sir

**Comment by faustinoaq** [comment]
Hi @girng You should install `libyaml-dev` in your WSL

Ref: https://github.com/crystal-lang/crystal/wiki/All-required-libraries#ubuntu
