### ISSUE TITLE
Clarify usage of database_url string

### ISSUE THREAD

**Issue by Blacksmoke16** [amberframework/granite#180]
1.  Add to readme that you can use `Granite::ORM.settings.database_url = "mysql://username:password@hostname:3306/database"` in code instead of ENV variable or the yaml file if so desired.

2.  Make a note it must be set **before** any models are declared (in the case of a single file).

**Comment by robacarp** [comment]
Someone mentioned in the gitter and I agree, I don’t think Granite should be responsible for reading config files or environment variables anymore. Granite as a library should only care to receive its connection information via its config interface.

**Comment by Blacksmoke16** [comment]
Wouldn't hurt to have it setup more like AR was in Ruby, where you can define different databases based on ENV, but general config was all in the yaml file.

**Comment by robacarp** [comment]
It seems like reading the ENV/config are outside the bounds of this library though, and should be handled by Amber (or whatever application is using Granite).

**Comment by elorest** [comment]
We do have conf files within amber for this. :)

**Comment by Blacksmoke16** [comment]
I been thinking of this, here are my thoughts.

Granite should decide upon one format for supplying a connection, such as `Granite::ORM.settings.database_url =  xxx`, or like Granite::ORM.Settings.new(host, port, db, ...) or what have you.  Granite should accept this format for defining which db should be used for the queries.  

Whatever application/framework you are using can have their own method of storing the information required(such as in environment, or a yaml file, or a string etc).  Wherever/how the parameters come to be supplied to Granite is outside the scope of Granite.

**Comment by drujensen** [comment]
Just to give some background, Granite was originally built in Kemalyst and the configuration was read from the `config/database.yml`.  When we migrated to Amber, we decided to include the database configuration in the environment (which totally makes sense) but I left the older style for people that was still using it.  

We can deprecate the `config/database.yml` and reading the environment stuff  and only support setting the `database_url` since its been over a year.

**Comment by Blacksmoke16** [comment]
@robacarp @drujensen @faustinoaq 

I'm thinking this will be my next PR, after some of my current ones are merged/closed so that I dont get into branch soup.

My plan for this is to deprecate the ENV and .yml config options in favor of Granite::ORM.settings.database_url = xxx`.  First by removing their implementations, but keeping the logic that accepts them in the base.cr adapter.  If the `Granite::ORM.settings.database_url = xxx` is nil (meaning they used one of the other methods) throw an exception telling them to switch.  Probably keep this exception there for a while then remove it.

This also brings up the idea of supporting multiple schemas/databases?  For example, having a `schema "foo"` macro, similar to `table_name` that would tell the adapter what schema/database should be used for that model?  

Are a few use cases i can think of that this would be useful for, but not sure if it would be something we would want to do

**Comment by Blacksmoke16** [comment]
I been messing around with this lately; got good and bad news.

The good news is multi database/schema is pretty trivial to do imo.  I have a working version of it on my local atm.

The bad news is currently our tests kinda depend on having the ENV variable to know what adapter to use when running the tests.  I can have the tests run by altering the ADAPTERS constant to run them 1 at a time adjusting the input as i move from one to another.  

One option would be to keep the ENV reading within granite but scope it to only for the tests.

I'll keep poking around and see i can come up with anything, then can make a PR and see what you guys think.  Worse comes to worse can save it for another day.

**Comment by robacarp** [comment]
@Blacksmoke16 I think it's reasonable to fix the tests by making a database.yml file which has a connection string for mysql, postgres, and sqlite and is parsed and used by a test helper. That would be the last attachment to the database.yml file, and then we could move forward in another pull for the other features.

**Comment by Blacksmoke16** [comment]
I'm going to make this my focus this weekend.

**Comment by Blacksmoke16** [comment]
Closing this in favor or #254
