### ISSUE TITLE
SELECT feature

### ISSUE THREAD

**Issue by jaysneg** [amberframework/granite#200]
add ability to edit SELECT of Query

Is not posible to add custom fields

SELECT *, **categories.name AS category_name** FROM products JOIN categories ON categories.id = products.category_id

like there: **https://apidock.com/rails/v4.0.2/ActiveRecord/QueryMethods/select**

**Comment by noahlh** [comment]
This is under discussion @ #184 

Working on it now!

**Comment by robacarp** [comment]
Closing as duplicate of #184
