### ISSUE TITLE
find_by feature

### ISSUE THREAD

**Issue by jaysneg** [amberframework/granite#206]
Add ability to select only one record by few params 
**Model**.find_by(name: name_string, other_field: other_field_int)

http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by

**Comment by Blacksmoke16** [comment]
We already support a `find_by` method, however it only accepts one key/value pair.  This would be fairly easy to do, refactor current `find_by` to accept multiples.

**Comment by Blacksmoke16** [comment]
I have a working version of this by adding an override to the current `find_by` but i don't like how the syntaxes are different.  Going to see if i can refactor them into one.
