### ISSUE TITLE
preload ability

### ISSUE THREAD

**Issue by jaysneg** [amberframework/granite#207]
Add ability to preload data from joined tables and make only one query like includes in Rails ActiveRecord 

https://apidock.com/rails/ActiveRecord/QueryMethods/includes

**Comment by jaysneg** [comment]
I think it the same [https://github.com/amberframework/granite/issues/65](https://github.com/amberframework/granite/issues/65)

**Comment by drujensen** [comment]
@jaysneg thanks for reporting this.  yes, this is a duplicate of #65.  closing.
