### ISSUE TITLE
Provide primary auto: UUID option that leverages Postgresql native support

### ISSUE THREAD

**Issue by pynixwang** [amberframework/granite#210]
`abstract def insert(table_name, fields, params, lastval) : Int64`

`insert` is limited to return `Int64`

**Comment by drujensen** [comment]
The return value is ignored if `auto: false` on `primary`

**Comment by drujensen** [comment]
right now, we only support the following:  https://github.com/amberframework/granite#uuids

**Comment by Blacksmoke16** [comment]
@pynixwang Do you have a different use case that isn't doable with current implementation?  Otherwise this is a non issue.

**Comment by pynixwang** [comment]
it 's not friendly if we must set callback manually, can this be done as a macro?

**Comment by Blacksmoke16** [comment]
Ah so you mean like declare `primary` as type `UUID` for example, and it would handle the creation/setting of UUID?

**Comment by pynixwang** [comment]
yes.

**Comment by pynixwang** [comment]
and will last_value have race condition while concurrent insert?

**Comment by Blacksmoke16** [comment]
@amberframework/granite-orm-contributors @pynixwang 

What would your thoughts be on refactoring the `auto: false`to say `type: xxx`.  Where it would default to `type:  auto`.  Other options would be `type: false` to disable auto int, or `type: UUID` to generate the UUID on model automatically?

**Comment by drujensen** [comment]
I still prefer `auto: ` but you could add `auto: UUID` to generate the UUID automatically.  This would allow us to take advantage of UUID in pg.

**Comment by Blacksmoke16** [comment]
I could go with that. :+1:

**Comment by pynixwang** [comment]
I prefer pg uuid generate, but mysql and sqlite can not do this, so generate in app layer is the more compatible.
