### ISSUE TITLE
Add sanitize method

### ISSUE THREAD

**Issue by jaysneg** [amberframework/granite#212]
sanitize sql query

http://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html
https://apidock.com/rails/ActiveRecord/Base/sanitize/class

**Comment by Blacksmoke16** [comment]
Im not sure this is needed, all the insert/update functions use prepared statements already so this is kinda redundant.

**Comment by jaysneg** [comment]
@Blacksmoke16 yes for raw SQL

**Comment by jaysneg** [comment]
or if try to save html code to description:text field

**Comment by jaysneg** [comment]
@Blacksmoke16
Incorrect string value: '\xE2\x81\x84<su...' for column 'description' at row 1 (DB::Error)

**Comment by Blacksmoke16** [comment]
I'm going to close this since this is outside the scope of Granite.  Consider making an issue on the base driver repo https://github.com/crystal-lang/crystal-db.
