### ISSUE TITLE
Validation helpers

### ISSUE THREAD

**Issue by Blacksmoke16** [amberframework/granite#217]
As of now the validators usage is not documented in the readme.  We should do that.

**Comment by Blacksmoke16** [comment]
@amberframework/granite-orm-contributors 

I think i want to take the time to add some helper wrapper validators.  For example:

`assert_not_nil :name` which would add the error `name cannot be nil` if name is nil

or

`assert_greater_than :age, 0` which would add the error `age must be greater than 0` if age is less than 0.

WDYT?

**Comment by Blacksmoke16** [comment]
So far to start i have:
greater than (or equal to)
less than (or equal to)
blank
not blank
nil
not nil
length
valid choice (preset list of possible values)

Any other good ones you think?

**Comment by faustinoaq** [comment]
@Blacksmoke16 Looks good, BTW, I think would be possible to create a `docs/` folder to separate granite sections and use them here: https://amberframework.gitbook.io/granite, WDYT?

**Comment by Blacksmoke16** [comment]
Assuming you mean delete the generated `docs` folder and replace it with a file per feature so that everything isn't in one big readme?  

I think that would be good but prob better suited to another issue.

**Comment by faustinoaq** [comment]
> Assuming you mean delete the generated docs folder and replace it with a file per feature so that everything isn't in one big readme?

Oh, I just realize `crystal docs` uses `docs/` folder :sweat_smile: , so, I think we can use something like a `guides/` directory, WDYT?

> I think that would be good but prob better suited to another issue.

Oh, ok no problem :+1:

**Comment by Blacksmoke16** [comment]
This is merged in now.  Going to close.
