### ISSUE TITLE
Create Granite documentation

### ISSUE THREAD

**Issue by faustinoaq** [amberframework/granite#223]
Hi @drujensen I think Granite's README is growing very fast, maybe we should maintain a separate directory (or repo) for docs like Crecto and Jennifer do, WDYT?

BTW, I already created a GitBook page for Granite here: ~~https://amberframework.gitbook.io/granite~~ (linked to this repo and using Granite's README)

Update: new link :tada: https://docs.amberframework.org/granite/

**Comment by Blacksmoke16** [comment]
At the very least a table of contents would help.
