### ISSUE TITLE
Get ready for Crystal 0.25.0

### ISSUE THREAD

**Issue by Blacksmoke16** [amberframework/granite#226]
With 0.25.0 coming soon, we need to update some things for the new version.

- [x]  Update Dockerfile since `crystal deps` is being removed. https://github.com/crystal-lang/crystal/pull/5544
- [ ]  Remove references of `JSON::Type`. https://github.com/crystal-lang/crystal/pull/5183
- [ ] `File.stat` is renamed to `File.info` https://github.com/crystal-lang/crystal/pull/5584
- [ ]  Read the changelog for anything I missed. https://github.com/bcardiff/crystal/blob/changelog/0.25.0/CHANGELOG.md

**Comment by robacarp** [comment]
@Blacksmoke16 thanks for putting together this list. I read through the list of breaking changes and did some grepping to check if things were needed, and added File.stat to your list.

In addition, I think this change will have some major effects on projects which use Granite: 
- Automatic type casting of literals: https://github.com/crystal-lang/crystal/pull/6074
