### ISSUE TITLE
validation helper specs need to be brought into modularized style

### ISSUE THREAD

**Issue by robacarp** [amberframework/granite#234]

**Comment by Thellior** [comment]
Do you mean that instead of an validator_helper_spec we should create spec files like validate_is_nil_spec.cr validate_is_blank_spec.cr?

**Comment by robacarp** [comment]
@Thellior good question. If the spec files are long enough, that's a great way to make them more readable.

These are the changes I'd like to see:

-  the presence of test models in the spec files (spec/spec_models.cr has _plenty_ and they should be used whenever possible)
- not using the [GraniteExample::Adapters pattern](https://github.com/amberframework/granite/blob/master/spec/granite/querying/find_by_spec.cr#L3-L5) to enforce that specs are run on all adapters.

**Comment by Blacksmoke16** [comment]
Reason i put them with the spec is they all contain validation helpers on them.  I didn't want other thinking they could be used in other normal tests and wonder why they fail if one of the validation helpers constraints isnt met.  

I'm not opposed to moving them all into the `spec_models.cr` file and naming them `ValidationHelperxxxx` however.

**Comment by drujensen** [comment]
I believe this has been done.  closing this.
