### ISSUE TITLE
Granite running under Sentry-run keeps creating connections till the pool is exhausted

### ISSUE THREAD

**Issue by rishavs** [amberframework/granite#239]
I am using a hosted psql db at ElephantSql as my database. It gives me 5 connections to the db. My app is a simple api on Kemal and Granite and Sentry-run. On starting the app, Granite keeps sending repeated connection requests (same query repeated over and over again) till my pool is exhausted.
![Image of connections](https://files.gitter.im/amberframework/amber/EsOm/image.png)
In this screengrab, I used ` User.migrator.drop_and_create` and ` Post.migrator.drop_and_create` in my code. If I remove these 2 lines, just calling my model is enough to saturate the pool.
    
This issue is not present if sentry-run is disabled. 

I am assuming that Granite goes into some loop when ran from within sentry.

I am really not sure if this bug goes here or in the sentry-run project...

**Comment by drujensen** [comment]
Interesting.  Sentry will restart the process if some code changes but I would think the previous connection would be disabled when the older process is killed.  Can you provide details on what sentry is monitoring?  Is there any files that might be triggering a sentry restart or can you confirm there is no restart happening?

**Comment by faustinoaq** [comment]
@rishavs What is your sentry config? Are you sure this is not an sentry-run issue? :sweat_smile:

**Comment by rishavs** [comment]
Sentry doesn't needs to restart. Just tried on a fresh crystan run.

````
#app.cr file
require "kemal"
require "sentry-run"
require "dotenv"
require "pg"
require "granite/adapter/pg"
require "crypto/bcrypt/password"

puts "Setting up the app ..."

puts "Reading env config"
Dotenv.load

puts "Initializing Database"


require "./models/*"
require "./routes/*"

module Kemapi

    # User.migrator.drop_and_create
    # Post.migrator.drop_and_create
    
    opts = Sentry.config(
        process_name: "kemapi",
        build_command: "crystal",
        run_command: "./bin/kemapi",
        build_args: ["build", "src/kemapi.cr", "-o", "bin/kemapi"],
        run_args: ["-p", "4321"]
    )
      
    Sentry.run(opts) do
        Kemal.run
    end
    # Kemal.run
end
````
and an example model;
````
module Kemapi
    class User < Granite::Base
        adapter pg

        field username :      String
        field password_hash : String
        
        timestamps

        validate_uniqueness :username
        validate_min_length :username, 3
        validate_max_length :username, 255

        validate_min_length :password_hash, 60
        validate_max_length :password_hash, 60

    end
end
````

**Comment by faustinoaq** [comment]
@rishavs Oh, I think this a sentry-run issue, because sentry forks a process in background, and maybe the process is not being killed properly :sweat_smile:

**Comment by rishavs** [comment]
my bad. That sounds about right.

**Comment by faustinoaq** [comment]
Also, be aware sentry-run code is pretty simple (just a few line of code), the actual code is on sentry repo :sweat_smile:
