### ISSUE TITLE
Implement ==(other) and <=>(other) on Base

### ISSUE THREAD

**Issue by robacarp** [amberframework/granite#243]
It'd be handy both for Granite specs and for application devs to be able to take an Array(MyModel) and call `#sort` on it, or be able to ask if two instances of a model are `==` each other.

**Comment by drujensen** [comment]
@robacarp I think this requires some knowledge of the business logic to determine if an object is less than or greater than another object.  I don't think we should try to implement this feature.  For example, you might use the `name` field for a `User` object but you would use the `zip code` for an `Address` object.
