### ISSUE TITLE
Undefined method 'import' for Class

### ISSUE THREAD

**Issue by SRod86** [amberframework/granite#245]
I'm not sure if I'm reading the docs incorrectly or if this is a true error. Not sure where else to check for errors on my end though.

I'm setting up basic authorization for an Amber app and have a User migration which has been run already (I logged directly into the DB to confirm this was successful). Upon running `amber db seed` to add users in bulk, I get: 

> Error in db/seeds.cr:11: undefined method 'import' for User:Class
> 
> User.import(users)

When reading this in the docs, I'm assuming I get the `import` method for free: 

>Each model has an import class level method to import an array of models in one bulk insert statement.

My seeds file for reference:
```
require "../config/application.cr"
users = [
  User.new(email: "admin@example.com", hashed_password: "password"),
  User.new(email: "user1@example.com", hashed_password: "password"),
  User.new(email: "user2@example.com", hashed_password: "password")
]

User.import(users)

```

**Comment by Blacksmoke16** [comment]
Can you give what your User class looks like?

**Comment by SRod86** [comment]
Granite version: 0.8.4

User class is pretty basic:
```
require "granite_orm/adapter/pg"
require "crypto/bcrypt/password"

class User < Granite::ORM::Base
  include Crypto
  adapter pg
  primary id : Int64
  field email : String
  field hashed_password : String
  timestamps

  validate :email, "is required", -> (user : User) do
    (email = user.email) ? !email.empty? : false
  end

  validate :email, "already in use", -> (user : User) do
    existing = User.find_by :email, user.email
    !existing
  end

  validate :password, "is too short", -> (user : User) do
    user.password_changed? ? user.valid_password_size? : true
  end

  def password=(password)
    @new_password = password
    @hashed_password = Bcrypt::Password.create(password, cost: 10).to_s
  end

  def password
    (hash = hashed_password) ? Bcrypt::Password.new(hash) : nil
  end

  def password_changed?
    new_password ? true : false
  end

  def valid_password_size?
    (pass = new_password) ? pass.size >= 8 : false
  end

  def authenticate(password : String)
    (bcrypt_pass = self.password) ? bcrypt_pass == password : false
  end

  private getter new_password : String?
end

```

**Comment by SRod86** [comment]
Ah, that'll do it haha. I'll definitely check out those helpers! Thanks!

**Comment by robacarp** [comment]
@SRod86 please note that `orm` is no longer part of the name of `Granite::Base`, nor is it part of the name of the shard.
