### ISSUE TITLE
Exception throwing variant `!` operator broken

### ISSUE THREAD

**Issue by rishavs** [amberframework/granite#248]
If I use the exception throwing version of save, I am getting errors;
````
in src/actions/auth.cr:11: undefined method 'save!' for Kemapi::User (did you mean 'save'?)

                new_user.save!
````
For me this code works as expected;
````
        def self.register (env)
            begin
                new_user = User.new
                new_user.username = env.params.body["username"].as(String)
                pass = env.params.body["password"].as(String)
                new_user.password_hash = Crypto::Bcrypt::Password.create(pass).to_s
                new_user.save
            rescue ex
                pp ex
                {
                    "status" => "error",
                    "message" => ex.message.to_s
                }
            else
                if new_user.errors.size > 0
                    {
                        "status" => "error",
                        "message" => new_user.errors[0].message.to_s
                    }
                else
                    {   "status" => "success",
                        "message" => "User was successfully registered!",
                        "data" => {
                            "unqid" => new_user.unqid, 
                            "username" => new_user.username
                        }
                    }
                end
            end
        end
````
but it breaks down when I use `new_user.save!` in the begin block as
````
            begin
                new_user = User.new
                new_user.username = env.params.body["username"].as(String)
                pass = env.params.body["password"].as(String)
                new_user.password_hash = Crypto::Bcrypt::Password.create(pass).to_s
                new_user.save!
            rescue ex
````

**Comment by Blacksmoke16** [comment]
What version of granite are you using?

**Comment by rishavs** [comment]
oops forgot to mention that. I am on 12.1

**Comment by Blacksmoke16** [comment]
This feature hasn't been released yet.  You would have to specify the master branch to get it.

**Comment by rishavs** [comment]
hmmm... should the docs be updated to account for it. They explicitly say that I can use the `!` operator.

**Comment by Blacksmoke16** [comment]
No.  The docs as you see on Github are based on the master branch of Granite source code, not what features are available based on a specific version of Granite via shards.  

Using the master branch in your shard.yml as the version is probably a bad idea as a breaking change could get merged into master and you're app would break.

**Comment by rishavs** [comment]
The amber gitbook docs give the same info. Maybe we should start versioning the docs so that such documentation errors don't come in. Whats your opinion on this?

**Comment by Blacksmoke16** [comment]
Pretty sure those docs are just pulling/based on the README of Granite master branch.  

That could be an option but probably best suited to its own issue.

**Comment by rishavs** [comment]
I will start a new one for that.
