### ISSUE TITLE
Add `# :nodoc:` to some properties/methods

### ISSUE THREAD

**Issue by Blacksmoke16** [amberframework/granite#251]
Quite a few Granite methods/constants pollute the generated docs.

For example i dont think `adapter` `table_name` `validate` `CALLBACKS` `CONTENT_FIELDS` etc should be included in the docs for classes using Granite.  All they do is pollute and quite frankly take over the generated docs for any class inheriting from `Granite::Base`

To clarify this would be docs generated via `crystal docs`

WDYT?

EDIT:  TIL we have an update method.

**Comment by Blacksmoke16** [comment]
@drujensen @robacarp Which option would you prefer.

1.  Always not generate them with a hardcoded `# :nodoc:`
2.  Generate by default but option to not using an ENV variable?

**Comment by robacarp** [comment]
I’d say simple is better. Docs are meant for easy access, I don’t see a reason to toggle the nodoc.

**Comment by Blacksmoke16** [comment]
Was more so thinking what if we wanted to use the generated docs as an API for Granite.  We would ofc want to show those methods/params/macros.  But someone using Granite for their project prob wouldn't want to.

Doesn't really matter to me.

**Comment by robacarp** [comment]
0h I see what you mean. Sure, yeah
