### ISSUE TITLE
Support adapter registration

### ISSUE THREAD

**Issue by drujensen** [amberframework/granite#254]
We should look at supporting registration of an adapter and then using that adapter by name in the model.  Right now we are hard coding the adapter names to `pg`, `mysql` and `sqlite` but I think we can fix this by allowing you to register your own named adapter and then using that named adapter in the model.

Registering a new adapter:
```
adapter = Granite::Adapter::Pg.new(
 name: "my_pg_adapter", 
 url: "postgres://localhost/database"
)
Granite.adapters << adapter
```
And then using it:
```
class MyModel < Granite::Base
  adapter my_pg_adapter
end
```

This will allow for other adapters in the future and support connecting to two of the same type of database as well.

**Comment by Blacksmoke16** [comment]
This is pretty much what @robacarp and @eliasjpr were talking about in my old PR.

See https://github.com/amberframework/granite/pull/242#issuecomment-400520029 and https://github.com/amberframework/granite/pull/242#issuecomment-400711014

**Comment by drujensen** [comment]
Correct, except this will support future adapters and handles multiple connections to the same type of database using the adapters registered name.
