### ISSUE TITLE
Problems compiling.

### ISSUE THREAD

**Issue by drinkmorewaters** [amberframework/granite#260]
cr:1: while requiring "granite/adapter/pg": can't find file 'granite/adapter/pg'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?

require "granite/adapter/pg"
^

Can't run Crystal build because of require error. I ran shards install.

**Comment by Blacksmoke16** [comment]
This isn't really helpful.  Is probably user error.

Would need to see some code examples.

**Comment by drinkmorewaters** [comment]
Most definitely user error as i literally started learning Amber today, with only a few days of programming experience. 

The DB seems to be linked as i can save passwords, sign in/sign up is working. 

I have attached the code in a zip file if that helps.
[my_blog_amber.zip](https://github.com/amberframework/granite/files/2214249/my_blog_amber.zip)

It seems to be included.

name: my_blog_amber
version: 0.1.0

authors:
  - your-name-here <your-email-here>

crystal: 0.25.1

license: UNLICENSED

targets:
  my_blog_amber:
    main: src/my_blog_amber.cr

  amber:
    main: lib/amber/src/amber/cli.cr

dependencies:
  amber:
    github: amberframework/amber
    version: 0.8.0
    #branch: master

  granite:
    github: amberframework/granite
    version: ~> 0.12.1

  quartz_mailer:
    github: amberframework/quartz-mailer
    version: ~> 0.5.1

  jasper_helpers:
    github: amberframework/jasper-helpers
    version: ~> 0.2.0

  pg:
    github: will/crystal-pg
    version: ~> 0.15.0

  citrine-i18n:
    github: amberframework/citrine-i18n
    version: 0.3.2

development_dependencies:
 garnet_spec:
   github: amberframework/garnet-spec
   version: ~> 0.2.1

**Comment by Blacksmoke16** [comment]
Welcome to Crystal :) Glad to have you on board.  I'll take a look and see what i see.

**Comment by drinkmorewaters** [comment]
@drujensen @Blacksmoke16 Thank-you for you quick help. Very embarrassing. I didn't write crystal build src/my_blog_amber.cr Missed the src/

Bit hard as a beginner as it's lots of poking, not much material for beginners out yet. So thank you very much for you help!

**Comment by Blacksmoke16** [comment]
Glad you figured it out, feel free to join the Gitter chat, might be easier for questions and such.

https://gitter.im/amberframework/amber
