### ISSUE TITLE
Registering driver not working

### ISSUE THREAD

**Issue by joenas** [amberframework/granite#282]
```
Exception: no driver was registered for the schema "", did you maybe forget to require the database driver? (ArgumentError)
```

I keep getting this in production with code that works just fine in development. 
I've tried every possible order when require-ing and registering adapter but nothing works. 

Right now this is what I have

```crystal
require "dotenv"
require "kemal"
Dotenv.load
Kemal.config.env = ENV["KEMAL_ENV"]

Granite::Adapters << Granite::Adapter::Pg.new({name: "postgres", url: ENV["DATABASE_URL"]})
require "db"
require "pg"
require "granite"
require "granite/adapter/pg"

require "rest-of-code"
```

Your "Getting started" says this: 

> Next you will need to register an adapter. This should be one of the first things in your main Crystal file, before Granite is required.

I'm running the app on dokku with Herokus buildpack. The database ENV is there, I even had a `puts` to make sure... so I'm lost. It's probably something trivial that I've overlooked but any help would be much appreciated.

**Comment by faustinoaq** [comment]
Hi @joenas try using `name: "pg"`:

```crystal
Granite::Adapters << Granite::Adapter::Pg.new({name: "pg", url: ENV["DATABASE_URL"]})
```

**Comment by faustinoaq** [comment]
> I keep getting this in production with code that works just fine in development.

Oh, I just missed this :sweat_smile: 

In this case, ensure `DATABASE_URL` is available in your code during production, try:

```cr
p! ENV["DATABASE_URL"]
```

**Comment by drujensen** [comment]
which version of Granite are you using?

**Comment by joenas** [comment]
I'm using `0.14.0`. I actually put the url to my docker container straight in the crystal file just to see if it worked and it did. So it's something with the `ENV` in dokku, could be that it's not escaped properly.. I doubt it's releated to granite though so I'll close this for now.

**Comment by joenas** [comment]
I sorted it out with `ENV["DATABASE_URL"].gsub("\"", "")` so there's that...
