### ISSUE TITLE
SQlite Versions

### ISSUE THREAD

**Issue by Blacksmoke16** [amberframework/granite#296]
Currently we are only testing the version of SQlite that comes with the crystal ubuntu install. `3.11.0`.  This is 14 minor versions behind the latest.

Would it be worth to test other versions, or at least use the latest version to test on?  I would like to use at least version `3.24.0` which added an upsert feature with the same syntax as PG uses.  

https://www.sqlite.org/lang_UPSERT.html

**Comment by drujensen** [comment]
> Would it be worth to test other versions, or at least use the latest version to test on? I would like to use at least version 3.24.0 which added an upsert feature with the same syntax as PG uses.

yes.  Rule of thumb is test the stable version and one version previous.

**Comment by Blacksmoke16** [comment]
👍 I'll look into doing this this weekend.  Would users who use sqlite be on the latest version?  i.e. if I were to refactor the bulk imports to use the new upsert feature, that would break people using older versions.
