### ISSUE TITLE
Compile error using granite and crystal 0.24.2 (LLVM 5.0.1) on raspberrypi

### ISSUE THREAD

**Issue by lebogan** [amberframework/granite#320]
Is this a Crystal or Granite error?

Syntax error in lib/granite/src/granite/callbacks.cr:7: expecting token ']', nit '::' @[JSON::Field(ignore: true)]

Thanks

**Comment by Jens0512** [comment]
It is because your crystal compiler is ancient :D, current version is 0.27.2. 
Update your crystal and this should be working

**Comment by lebogan** [comment]
Thanks @Jens0512 . Since this is what I can get for the armhf architecture, I'm going to have to come up with something else, maybe cross-compile. Yuk!

**Comment by Jens0512** [comment]
Couldn't you just build the compiler yourself?
