### ISSUE TITLE
Shard name mismatch

### ISSUE THREAD

**Issue by lebogan** [amberframework/granite#328]
Updated my Kemal-based application to Crystal 0.28.0. Ran shards update and got the following error message:
```
Error shard name (kemalyst-model) doesn't match dependency name (granite)
```
My shard.yml entry:
```
  granite:
    github: amberframework/granite
```
I have manually removed the granite shard from cache and run `shards install` with the same error. What is the reference to `kemalyst-model`?

As always, I greatly appreciate any and all help from this great community. Keep it up!

**Comment by lebogan** [comment]
On further investigation:
```
  granite:
    github: amberframework/granite
    version: ~> 0.15.0
```
Specifying the version works. This appears to be my lack of understanding of the shards dependency manager. I am going to close this issue.

**Comment by elorest** [comment]
Thanks for the update. I would have assumed it would use the latest version if not specified.

**Comment by carcinocron** [comment]
After trying this I get:
```
In lib/granite/src/granite/settings.cr:1:1

 1 | require "logger"
     ^
Error: can't find file 'logger'

If you're trying to require a shard:
- Did you remember to run `shards install`?
- Did you make sure you're running the compiler in the same directory as your shard.yml?
```

**Comment by robacarp** [comment]
@carcinocron this issue is from 2019 -- if you're having trouble getting Granite working, please open a new issue.
