### ISSUE TITLE
Crystal 0.28.0 support

### ISSUE THREAD

**Issue by lebogan** [amberframework/granite#329]

**Comment by lebogan** [comment]
Using the --warnings flag to build one of my cli-based apps, I get a warning about using `Time.local` or `Time.utc` instead of `Time.now` in `lib/granite/src/granite/transactions.cr`. 

As this has been noted as a breaking change (depreciation) by the Crystal team, I updated my local copy and recompiled. 

Is this something to be overly concerned about?

**Comment by Blacksmoke16** [comment]
@lebogan These are just warnings letting you know they are deprecated and will be removed in a _future_ version.  It does not affect Granite's ability to work on `0.28.0`; just that we will want to replace the usages for the next crystal version.

**Comment by Blacksmoke16** [comment]
@lebogan However I'll submit a PR to take care of this and update CI to use `0.28.0`.
