### ISSUE TITLE
Include associations when calling to_json

### ISSUE THREAD

**Issue by dkniffin** [amberframework/granite#331]
I'm looking for the ability to serialize associations. For example, if I've got the following classes:

```cr
class Person < Granite::Base
  adapter pg
  table_name people

  belongs_to :family

  primary id : Int64
  field name : String
  timestamps
end

class Family < Granite::Base
  adapter pg
  table_name families

  has_many :members, class_name: Person

  primary id : Int64
  timestamps
end
```

and then I set up some objects:

```cr
fam = Family.new
fam.save

john = Person.new(name: "John")
john.family = fam
john.save
jane = Person.new(name: "Jane")
jane.family = fam
jane.save
```

when I serialize it (with `fam.to_json`), I'd like to have a way to include the associations (members, in this case). As far as I can tell, currently just includes attributes (id and timestamps).

I may be missing something, in which case great! Then the fix would be just documentation. Otherwise, if someone wants to point me to the right place to add this functionality, I'd be happy to make a PR.

**Comment by dkniffin** [comment]
Another possible solution would be a separate serialization library, where I can create serializer classes that get used, similar to [ActiveModelSerializers](https://github.com/rails-api/active_model_serializers)

**Comment by Blacksmoke16** [comment]
Granite serialization is built on top of JSON/YAML::Serializable in the standard library.  In order to support this you could simply define an `on_to_json(builder : JSON::Builder)` method to add that field.

```
def on_to_json(builder : JSON::Builder)
  builder.field "members", self.members
end
```

This would include a `"members"` property in the json output with a value of your members.

**Comment by dkniffin** [comment]
Interesting. I'm still very new to Crystal. Do you have a link to the docs on this? Also, I think it'd be good to call that out in the granite and/or amber docs somewhere.

**Comment by Blacksmoke16** [comment]
It already is, the first line in the [json support](https://github.com/amberframework/granite/blob/master/docs/json_support.md#json-support), but it seems I missed documenting the `on_to_json`.  I'll make a PR to update that file to include an example of it.

**Comment by dkniffin** [comment]
Yeah, that would be a good example to have. Thanks!

**Comment by rmarronnier** [comment]
Hmm, would it be possible to have : 
`has_many :members, class_name: Person, json_options: {include: true}`
?
That would be cleaner / more elegant (?)

**Comment by Blacksmoke16** [comment]
Maybe yes, but it would increase the effort required to close this issue by a lot.

If you/someone can figure out a good way to implement it feel free to open a PR, but for now, just documenting this is prob good enough.
