### ISSUE TITLE
One request - Many objects

### ISSUE THREAD

**Issue by alex-lairan** [amberframework/granite#339]
Hi !

I'm using Granite, and I have a problem with joins.

Here my code : 

```
      surveys = Survey.all(<<-SQL)
        JOIN survey_questions sq on sq.survey_id = surveys.id
        JOIN survey_responses sr on sr.survey_question_id = sq.id
      SQL
```

`surveys.first.questions` should not request the database, but it does.
Same for `surveys.first.questions.first.responses`.

My serializer is like that : 

```
require "crinder"

class Survey::ResponseSerializer < Crinder::Base(Survey::Response)
  field id! : Int64, as: id
  field text : String

end

class Survey::QuestionSerializer < Crinder::Base(Survey::Question)
  field id! : Int64, as: id

  field question : String

  field responses, with: Survey::ResponseSerializer, value: ->{ object.responses.to_a }
end

class SurveySerializer < Crinder::Base(Survey)
  field id! : Int64, as: id
  field name : String

  field questions, with: Survey::QuestionSerializer, value: ->{ object.questions.to_a }

  field created_at : String
  field updated_at : String
end
```

How I need to change my code to do only one request ? Because `n+1` takes long :/

**Comment by drujensen** [comment]
Not yet. You are looking for `includes` or eager loading.  See ticket #65 

Your best option is to query each of these tables separately.  Not sure how to get those into your serializers though.
