### ISSUE TITLE
Error in docs about deletion

### ISSUE THREAD

**Issue by EnricoMonese** [amberframework/granite#347]
Not too important but it caused me some headaches because I thought it was not working.

[I'm talking about this exampe](https://github.com/amberframework/granite/blob/master/docs/crud.md#L109)
with this code
```crystal
post = Post.find 1
post.destroy
puts "deleted" unless post
```

It seems the `unless` parts no longer works as intended, since I never got any output.

Also related #145, could be accounted in the docs 👍 

It could be better maybe a bit like this:

```crystal
post = Post.find 1
post.destroy if post
puts "deleted" if post.destroyed?
```

**Comment by Blacksmoke16** [comment]
Correct, could you make a PR?

**Comment by EnricoMonese** [comment]
Made a PR #348 👍
