### ISSUE TITLE
Are Converter docs right?

### ISSUE THREAD

**Issue by EnricoMonese** [amberframework/granite#349]
Are the Converter docs right, is there anything else to do to use this feature?
I even tried the example provided but it doesn't seem to work 

```
no overload matches 'Array(Array(Bool) | Array(Float32) | Array(Float64) | Array(Int16) | Array(Int32) | Array(Int64) | Array(String) | Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil)#<<' with type (OrderStatus | Nil)
Overloads are:
 - Array(T)#<<(value : T)
Couldn't find overloads for these types:
 - Array(Array(Bool) | Array(Float32) | Array(Float64) | Array(Int16) | Array(Int32) | Array(Int64) | Array(String) | Bool | Float32 | Float64 | Int32 | Int64 | Slice(UInt8) | String | Time | Nil)#<<(value : OrderStatus)
```

**Comment by Blacksmoke16** [comment]
They should be.  Got some example code?

**Comment by EnricoMonese** [comment]
Ah yes, now it works. Does it default to the latest release tag otherwise?

Also I've had some minor things to fix though.
The `\` at the end of the line [here](https://github.com/amberframework/granite/blob/master/src/granite/association_collection.cr#L41) was giving errors, removing it fixed it.
And I had to add `require "uuid"` [here](https://github.com/amberframework/granite/blob/master/src/granite/fields.cr#L5) because it couldn't find it .
Should I make PRs for these?

**Comment by Blacksmoke16** [comment]
Yea if you would.  Kinda concerning CI didnt pick these up?

**Comment by EnricoMonese** [comment]
This can be closed then

**Comment by EnricoMonese** [comment]
The weird thing about the `\` is that it should be needed for the multiline string

**Comment by Blacksmoke16** [comment]
Oh, then there must be something else going on.  What was the granite version you're using?

Also what crystal/os?

I'm mainly wondering why CI didn't error but it did for you.  Might be worth looking into.

**Comment by EnricoMonese** [comment]
```
  granite:
    github: amberframework/granite
    commit: c4bc435fc9a24a132ff349367ba2b324d22d8948
```
```
Crystal 0.29.0 (2019-06-06)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

And I'm on macOS 10.13.6 (High Sierra)

**Comment by EnricoMonese** [comment]
Could be related to https://github.com/crystal-lang/crystal/issues/5831 ?

**Comment by EnricoMonese** [comment]
Yes that is the problem, I converted the line endings and now it works

**Comment by Blacksmoke16** [comment]
That would do it.  

I'll fix the uuid thing in the PR i have open.  Think I know why CI didn't pick it up.
