### ISSUE TITLE
cannot set `belongs_to` column using `new` or `set_attributes`

### ISSUE THREAD

**Issue by drujensen** [amberframework/granite#355]
I have a model:
```
class Comment < Granite::Base
  connection mysql
  table comments

  belongs_to :user
  belongs_to :post

  column id : Int64, primary: true
  column body : String?
  timestamps
end
```

When I try to set the `post_id` using `new` or `set_attributes`, it doesn't set.
```
params = {post_id: 1, body: "test"}
comment = Comment.new(params.to_h)
comment.to_h

{"user_id" => nil, "post_id" => nil, "id" => nil, "body" => "test", "created_at" => nil, "updated_at" => nil}
```

A work around is to lookup the `post` and set it directly:
```
params = {post_id: 1, body: "test"}
comment = Comment.new(params.to_h)
comment.post = Post.find! params[:post_id]
comment.save
```

**Comment by Blacksmoke16** [comment]
@drujensen This isn't actually a bug.  By default we define FKs as `Int64?`, you're passing in an `Int32`.  It's adding an error.

```cr
@errors=
  [#<Granite::Error:0x1093b8930
    @field="post_id",
    @message=
     "Expected post_id to be (Int64 | Nil) but got (Int32 | String).">],
```

If anything this would be a change in how we handle errors.  I.e. raise an exception when this happens or something along those lines?

**Comment by drujensen** [comment]
We must have handled this before.  This is going to be problematic for Amber Controllers if we need to convert the type to `i64` for every id.

**Comment by drujensen** [comment]
Looks like `save` is not returning false:
```
  def create
    post = Post.new post_params.validate!
    if post.save
      redirect_to action: :index, flash: {"success" => "Created post successfully."}
    else
      flash[:danger] = "Could not create Post!"
      render "new.slang"
    end
  end
```

**Comment by Blacksmoke16** [comment]
It should be, the logic around `#save` hasn't changed.

https://github.com/amberframework/granite/blob/master/src/granite/transactions.cr#L191-L196

**Comment by drujensen** [comment]
Ok.  Something strange is going on.  In Amber we have a controller:
```
   def create
    comment = Comment.new comment_params.validate!
    if comment.save
      redirect_to action: :index, flash: {"success" => "Created comment successfully."}
    else
      flash[:danger] = "Could not create Comment!"
      render "new.slang"
    end
  end

  private def comment_params
    params.validation do
      required :user_id
      required :post_id
      required :body
    end
  end
```
The `validate!` returns a hash of the params passed in.

The params are properly being set according to the logs so its not the view:
```
03:21:46 Params     | user_id: 1
03:21:46 Params     | post_id: 1
03:21:46 Params     | body: Testing
```

But the Granite insert statement is showing `nil` values for the foreign keys:
```
INSERT INTO `comments` (`user_id`, `post_id`, `body`, `created_at`, `updated_at`) VALUES (?, ?, ?, ?, ?): [nil, nil, "Testing", 2019-08-15 03:21:46.0 UTC, 2019-08-15 03:21:46.0 UTC]
```

**Comment by drujensen** [comment]
I jumped to the conclusion this was Granite related since that is the only thing that really changed.  I will keep investigating to see if I can track down what is causing this.

I verified that the `id's` being passed are `Int64` so my initial bug report is incorrect.  I will close this and open a new one if I can determine what is the cause.

Thanks for looking into this.
