### ISSUE TITLE
belongs_to fails to assign value when passed in as Hash of String's

### ISSUE THREAD

**Issue by drujensen** [amberframework/granite#356]
If I have a class:
```
class Post < Granite::Base
  connection mysql
  table posts

  belongs_to :user

  column id : Int64, primary: true
  column title : String?
  column body : String?
  timestamps
end
```

Then I try to create a new `post` in an Amber controller using the params:
```
params = {"user_id" => "1", "title" => "test", "body" => "test"}
post = Post.new params
puts post.save
puts post.to_json
```

The insert sets the `user_id` as `nil`
The `save` returns `true`
The `user_id` is not properly set

Here are the results:
```
06:08:37 Granite [42.0ms] INSERT INTO `posts` (`user_id`, `title`, `body`, `created_at`, `updated_at`) VALUES (?, ?, ?, ?, ?): [nil, "test", "test", 2019-08-16 01:08:37.0 UTC, 2019-08-16 01:08:37.0 UTC]
true
{"id":6,"title":"test","body":"test","created_at":"2019-08-16T01:08:37Z","updated_at":"2019-08-16T01:08:37Z"}
```

@Blacksmoke16 This used to work before the recent changes. Any idea's on the best way to resolve this?

I'm hoping that we don't have to generate special code to handle `belongs_to` params in the controllers.

**Comment by Blacksmoke16** [comment]
There are two issues at play here.

One being a bug in that the validator is only validating against the defined validators.  It clears the errors before doing so, thus not catching this type mismatch error.  To handle this I think we can either be more strict around type mismatches, raising an exception for example, or make sure the errors array isn't empty when seeing if the model is valid.

The other issue is related to how we're not longer doing implicit conversions of like `"1"` to `1`.  I think ideally Amber should start providing the model proper types.  However, another option would be to add support for `String => T` converters; which would be added to the `type.cr` file and work similarly to how the `Bool` one works.

**Comment by drujensen** [comment]
@Blacksmoke16 I see you added `status:wip` label.  Are you going to take a stab at this?  Looks like you may be able to leverage some of the work you did in athena.  If not, I will make an attempt at it.

**Comment by Blacksmoke16** [comment]
Yea I can fix it this weekend.  However we should come to a decision on which option we should choose for each issue.

**Comment by drujensen** [comment]
@eliasjpr and I talked about having the params use the proper types instead of just a Hash of Strings for everything.  It goes a little against DRY principles if we have the fields and types defined twice, but I can see wanting to validate the param types in the controllers instead of down in the models.  I could go either way. 

@eliasjpr @elorest wdyt?

**Comment by drujensen** [comment]
@Blacksmoke16 I think for now, we should restore the existing functionality and handle the conversion in Granite.

Regarding the errors, I feel like if we decide to handle the conversion, then we should generate an error in the validation array when there is a failure to convert from `String -> T` expected.  So for example, if someone tries to send in a String of `hello` to an `Int64` type field, it should generate an error for this column that it could not convert.  wdyt?

**Comment by Blacksmoke16** [comment]
Should be doable yes.  However IMO it's less than ideal Amber is relying upon an ORM to convert params to their correct types.  I feel like that should be something that happens prior to newing up a model, but idk how much work that would be.  I'm okay with bringing that back for now.
