### ISSUE TITLE
How to map JSON/JSONB from Postgres

### ISSUE THREAD

**Issue by igor-alexandrov** [amberframework/granite#360]
I have a JSONB column and currently map it into model as `Hash(String, String)` like:

```ruby
class FileImport < Granite::Base
  connection pg
  table file_imports

  column id : Int64, primary: true
  column asset_data : Hash(String, String)
end
```

What is the correct way to map JSON?

**Comment by Blacksmoke16** [comment]
Does that actually work?  I'd be surprised if it actually did.  Either way, you have a few options.  

First, if you want to have your data be an actual object you could do like 

`column asset_data : MyType, column_type: "JSONB", converter: Granite::Converters::Json(MyType, JSON::Any)`

Where you would define a class `MyType` that represents the data, then when you save it Granite would call `.to_json` on it.  When you read it Granite would use `.from_json`.

The other option would be to just use `String` if all you want is a reference the plain JSON string.
