### ISSUE TITLE
Can't set a field to nil

### ISSUE THREAD

**Issue by faissaloo** [amberframework/granite#368]
This is in Granite 0.17.2 with Postgres.  
`post.update(parent: nil)` generates the following statement:
```
UPDATE "posts" SET "parent"=$1, "message"=$2, "last_reply"=$3, "updated_at"=$4 WHERE "id"=$5: [8, "aeuo", nil, 2019-10-03 19:27:00.0 UTC, 9]
```
It seems to be trying to update with the values it already has, changing nothing, the field is marked nillable and this wasn't an issue in previous versions. Trying to change the field to another integer works fine.

**Comment by Blacksmoke16** [comment]
What happens if you do:

```cr
post.parent = nil
post.save
```

Also, could you share your model?

**Comment by faissaloo** [comment]
When I do that it generates the correct query.
`UPDATE "posts" SET "parent"=$1, "message"=$2, "last_reply"=$3, "updated_at"=$4 WHERE "id"=$5: [nil, "aeuo", nil, 2019-10-03 19:40:28.0 UTC, 9]`
My model is here: https://github.com/faissaloo/ratmachine/blob/master/src/models/post.cr
