### ISSUE TITLE
Wouldn't it be nice if the callbacks were just simply overridden methods?

### ISSUE THREAD

**Issue by u89012** [amberframework/granite#378]
Instead of hooking them manually to a method, wouldn't it be nice to just be able to override the before_* and after_* methods in model classes (if they were) inherited from Granite::Base? Any thoughts anyone?

**Comment by Blacksmoke16** [comment]
The problem with that is what if you wanted to do two things within the same callback?  You would have to either combine logic into the one method, or make two private methods to call within the one callback method.

IMO, I would rather opt for something like:

```cr
@[Granite::BeforeSave]
def hash_password
  @password = # Hash the password before saving
end
```
