### ISSUE TITLE
Sqlite3 Exception when database name contains a colon

### ISSUE THREAD

**Issue by 3n-k1** [amberframework/granite#394]
The following code produces a table with the name `cwiki::user`

```crystal
module Cwiki
  class User < Granite::Base
  end
end
```

This is an issue as statements that reference the table look something like this: "SELECT * FROM cwiki::user". Sqlite throws errors on table names that contain a colon unless the name is surrounded by quotation marks.

I think this should be an easy fix, but I'm not familiar with this codebase. I'll fork and check it out and report back if I figure things out.

**Comment by Blacksmoke16** [comment]
In this case, it's probably better to manually define the name of the table you want.  via `table "users"`. 

In regards to this bug, I'd imagine we would want to strip out the namespace of the type when creating the default table name.

That happens https://github.com/amberframework/granite/blob/master/src/granite/table.cr#L48

Could fix it by doing like `@type.name.underscore.stringify.split("::").last`.

**Comment by 3n-k1** [comment]
That leaves the question of "what happens when two tables have the same name?". Keeping the namespace would solve that issue.

**Comment by Blacksmoke16** [comment]
🤔 is that really a common use case?  IMO users should just set their table name with the `table` macro and be done with it.  Relying upon the namespace of your model can be brittle if you later decide to say wrap your stuff in an `API` module.  Also different database schemas/databases would better solve that as well.

**Comment by 3n-k1** [comment]
That's a really good point. I'll look into stripping the namespace now.
