### ISSUE TITLE
Implement firstOrCreate on models

### ISSUE THREAD

**Issue by Serdnad** [amberframework/granite#400]
In my current application, I find myself doing something like:
```cr
if !User.where(name: "John Doe", color: "red").exists?
  User.create(name: "John Doe", color: "red")
end
```
quite a bit, and thought it would be convenient to have a `first_or_create` method, [inspired by Rails]("https://apidock.com/rails/ActiveRecord/Relation/first_or_create").

It could potentially be done with
```cr
# Option 1
User.first_or_create(name: "John Doe", color: "red")

# Option 2
User.where(name: "John Doe", color: "red").first_or_create
```

I personally think the latter fits a little nicer, but I'm curious to see if this is something that others would be interested in, before working on it and opening a PR.

**Comment by Blacksmoke16** [comment]
This'll be available for in the next release.

See https://github.com/amberframework/granite/blob/master/src/granite/integrators.cr

**Comment by Serdnad** [comment]
@Blacksmoke16 Thanks for the quick answer! Glad to see it's already been done, guess I didn't find it because of the difference in name.

I noticed the relevant commit was made June of last year, and I couldn't easily find any indication of when the next release would be. Would you happen to have any idea when the next release might be, or point me to where I might find that info? Thanks again.

**Comment by Blacksmoke16** [comment]
Prob soon given it includes some `0.34.0` compatibility features.

\cc @drujensen
