### ISSUE TITLE
Logging in Crystal 0.35.1

### ISSUE THREAD

**Issue by lebogan** [amberframework/granite#411]
Little help, please. This worked pre 0.34.0:
```
  Granite.settings.logger = Logger.new(nil) # suppress debug output from production.
```
Getting this error:
```
Error: wrong number of arguments for 'Log.new' (given 1, expected 3)
Overloads are:
 - Log.new(source : String, backend : Backend | ::Nil, level : Severity)
```
I'm using the master branch in shards.yml while waiting on a new release. How do I fix this in the meantime.

Thank you.

**Comment by Blacksmoke16** [comment]
Granite uses https://crystal-lang.org/api/master/Log.html now since `Logger` is deprecated.  To answer your question, you would want to do `Log.setup :none`.  However this isn't really a Granite issue so I'm going to close.
