### ISSUE TITLE
Foreign key to same table

### ISSUE THREAD

**Issue by yujiri8** [amberframework/granite#418]
I won't be surprised if this is something I'm doing wrong, but I really can't figure it out.

I'm trying to represent a comment tree. The Comment model has a `reply_to` field which is a foreign key to its parent. The `dict` method returns a hash to be converted to JSON (I don't serialize the model directly because I need the `recursion` parameter and a few others that I took out to simplify the example), and the serialized Comment has a `replies` field that can hold a list of comments of the same structure.

```crystal
require "granite/adapter/pg"

Granite::Connections << Granite::Adapter::Pg.new(name: "db", url: "postgres://test@localhost/test")

class Comment < Granite::Base
  connection db
  table comments
  column id : Int32, primary: true
  belongs_to parent : Comment, foreign_key: reply_to : Int32?
  has_many replies : Comment
  alias CommentJson = Int32 | Nil | Array(Hash(String, CommentJson))
  def dict(recursion = 5) : Hash(String, CommentJson)
    {
      "id" => @id,
      "replies" => recursion ?
        self.replies.map &.dict(recursion: recursion - 1)
        : self.replies.size
    } of String => CommentJson
  end
end

Comment.find!(1).dict
```
I am getting:
```
Unhandled exception: column comments.comment_id does not exist (PQ::PQError)
  from lib/pg/src/pq/connection.cr:214:7 in 'handle_error'
  from lib/pg/src/pq/connection.cr:197:7 in 'handle_async_frames'
  from lib/pg/src/pq/connection.cr:162:7 in 'read'
  from lib/pg/src/pq/connection.cr:157:7 in 'read'
  from lib/pg/src/pq/connection.cr:408:31 in 'expect_frame'
  from lib/pg/src/pq/connection.cr:407:5 in 'expect_frame'
  from lib/pg/src/pg/statement.cr:18:5 in 'perform_query'
  from lib/db/src/db/statement.cr:88:14 in 'perform_query_with_rescue'
  from lib/db/src/db/statement.cr:78:7 in 'query:args'
  from lib/db/src/db/pool_statement.cr:29:30 in 'query:args'
  from lib/db/src/db/query_methods.cr:46:7 in 'query:args'
  from lib/db/src/db/query_methods.cr:61:7 in 'raw_all'
  from lib/granite/src/granite/querying.cr:32:30 in '->'
  from ../../../usr/lib/crystal/primitives.cr:255:3 in 'collection'
  from lib/granite/src/granite/collection.cr:2:3 in 'dict'
  from src/main.cr:12:3 in 'dict'
  from src/main.cr:22:1 in '__crystal_main'
  from ../../../usr/lib/crystal/crystal/main.cr:105:5 in 'main_user_code'
  from ../../../usr/lib/crystal/crystal/main.cr:91:7 in 'main'
  from ../../../usr/lib/crystal/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```
I've seen this `foreign_key: ` annotation work as expected with foreign keys to other tables, but when it's on the same table it seems to still assume the foreign key is called `comment_id`.

**Comment by Blacksmoke16** [comment]
Try doing like `belongs_to parent : Comment, foreign_key: reply_to : Int32?, primary_key: "reply_to"`

**Comment by yujiri8** [comment]
It didn't change anything. I also tried putting the `primary_key: "reply_to"`on the `has_many`, and that also didn't change it.

Shouldn't the `primary_key` of relationship be ID, since that's the key being pointed to?

**Comment by yujiri8** [comment]
I think I solved this. I needed to have `foreign_key: "reply_to"` or `foreign_key: :reply_to` on the `has_many` association. Looking back at the docs, it seems like this was clear (my fault) so I guess I'll close this.
