### ISSUE TITLE
Log level is set too high

### ISSUE THREAD

**Issue by HenryBaragar** [amberframework/granite#423]
In my opinion, there is no need to log every database query at the INFO level:  it drowns out other INFO level message in my applications.

I think that VERBOSE is the appropriate level for these messages.

**Comment by Blacksmoke16** [comment]
https://github.com/amberframework/granite/blob/master/src/adapter/base.cr#L32

At the moment queries are logged at the `DEBUG` level.  Are you seeing something different?

**Comment by HenryBaragar** [comment]
This is what I see:

2020-09-15T12:21:00.534265Z   INFO - granite: SELECT id, moniker, symbol, type, date, market, listing_market, lot_size FROM security_snapshots WHERE date = ? ORDER BY id DESC
2020-09-15T12:21:00.534307Z   INFO - granite: ["2020-09-15"]

My shard.lock shows:

    version: 0.21.0

**Comment by Blacksmoke16** [comment]
Ah it's coming from the query builder code: https://github.com/amberframework/granite/blob/master/src/granite/query/executors/base.cr#L8.

I'd be open to a PR to drop that down to verbose along with the other location.  Debug was the lowest level at the time.

**Comment by HenryBaragar** [comment]
How do I open a PR?

BTW, VERBOSE is DEBUG and INFO, meaning that changing the other spot actually will be moving it the other direction (which probably is appropriate)

**Comment by Blacksmoke16** [comment]
@HenryBaragar Never mind, I just went ahead and fixed it https://github.com/amberframework/granite/pull/424.
