### ISSUE TITLE
Objects representing the same record don't compare as equal

### ISSUE THREAD

**Issue by yujiri8** [amberframework/granite#430]
Is this intended?

```crystal
Granite::Connections << Granite::Adapter::Sqlite.new(name: "db", url: "sqlite3:./thing.db")

require "granite/adapter/sqlite"

class Thing < Granite::Base
  connection db
  table things
  column id : Int64, primary: true
  column name : String
end

a = Thing.find! 1
b = Thing.find! 1
puts a == b
puts a.id == b.id
```
Output:
```
false
true
```

**Comment by yujiri8** [comment]
Note that in this case, the objects not only have the same primary key but are identical in all properties, yet don't compare as equal.

**Comment by Blacksmoke16** [comment]
Can you provide the output of:

```cr
pp a
pp b
```

**Comment by Blacksmoke16** [comment]
Actually I think this is expected.  https://play.crystal-lang.org/#/r/9s7c

Two classes are only equal when they're the same instance.  See https://crystal-lang.org/api/Reference.html#==(other:self)-instance-method.

**Comment by yujiri8** [comment]
Oh I see. I was surprised because SQLAlchemy considers them equal, and because I saw that Crystal arrays compare as equal if they have the same elements. I guess I'll close this.
