### ISSUE TITLE
Migrator doesn't support Enums

### ISSUE THREAD

**Issue by wonderix** [amberframework/granite#432]
*Problem*

The following code 

```crystal
Granite::Connections << Granite::Adapter::Sqlite.new(name: "default",url: "sqlite3::memory:")

enum LogLevel
  Error
  Warning
  Info
  Debug
end 

class LogMessage < Granite::Base
  connection default
  column id : Int64, primary: true
  column level : LogLevel = LogLevel::Info, converter: Granite::Converters::Enum(LogLevel, String)
end

LogMessage.migrator.create

```

Produces

```
Unhandled exception: Migrator(Granite::Adapter::Sqlite) doesn't support 'LogLevel' yet. (Exception)
  from lib/granite/src/granite/migrator.cr:44:50 in '->'
  from ../../../../usr/local/Cellar/crystal/0.35.1_1/src/primitives.cr:255:3 in 'create_sql'
  from lib/granite/src/granite/migrator.cr:86:7 in 'create'
```

**Comment by Blacksmoke16** [comment]
The migrator is more of an internal thing used to testing Granite itself.  You'd be better off using https://github.com/amberframework/micrate or something similar.

Refs:
* https://github.com/amberframework/granite/issues/421#issuecomment-686085633
* https://github.com/amberframework/granite/issues/182
* https://github.com/amberframework/granite/pull/413

**Comment by wonderix** [comment]
@Blacksmoke16, thanks for the fast response. For clarification I created a PR #433 to change the documentation accordingly.
