### ISSUE TITLE
through in has_many doesn't work

### ISSUE THREAD

**Issue by confact** [amberframework/granite#460]
Hi

I try to do a has_many through relationship, like this:
```crystal
class User < Granite::Base
  ....
  has_many albums : Album
  has_many :photos, class_name: Photo, through: :albums
end
```
and the album has:
```crystal
class Album < Granite::Base
  ...
  belongs_to user : User, foreign_key: user_id : Int32?
  has_many photo : Photo
end
```
and photo:
```crystal
class Photo < Granite::Base
  ...
  belongs_to album : Album, foreign_key: album_id : Int32?
end
```

But when I do this:
```
user.photos
```
I get nothing,
user.albums gives me a list of the albums, and Photo.first give me the first photo, with correct album_id.

**Comment by stufro** [comment]
I'm not sure this is a bug, I think you might be misunderstanding how `has_many through:` works. It is used for many-to-many relationships, using your example this would be where a user `has_many :photos` and a photo `has_many :users` which is different to what's described above. See [this section of the docs](https://github.com/amberframework/granite/blob/master/docs/relationships.md#has_many-through) for a full example.

@crimson-knight I think this issue can be closed. Do you agree?

**Comment by crimson-knight** [comment]
@stufro yeah I think you're right. I think the confusion here lies in that Rails/ActiveRecord does let you do one-to-many relationships like in this example, which is not how Granite works.
