### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by robacarp** [amberframework/granite#462]
Granite remains one of the first landing places for new developers coming into crystal. It was a busy project for some time and has a wealth of technical implementation for abstracting away the differences between relational databases. At this time the developers (myself included) don't have the time to volunteer in the ways that the project needs.

If you're willing to participate in maintainership, please leave a message here or get in touch in Discord (`@rob` on [Crystal discord](https://discord.gg/YS7YvQy)). You don't need to be a grand master developer or have infinite free time -- the community around here is generally willing to contribute patches.

**Comment by AlexanderPankiv** [comment]
@robacarp I might be interested :)

**Comment by hugopl** [comment]
I plan to use granite in a new project, Avram is more well maintained, however I like the ActiveRecord approach for ORM better than the Avram approach.

So hope I can contirbute with PRs in a near future.
