### ISSUE TITLE
Import data maintaining timestamps

### ISSUE THREAD

**Issue by ggtrigg** [amberframework/granite#481]
I'd like to be able to import data from another database and keep the created_at & updated_at times. From everythig I've tried it seems like granite always overrides these on create even if those values are explicitly provided.

**Comment by crimson-knight** [comment]
You should be able to do bulk imports using `import` interface and not have it override the timestamps
https://github.com/amberframework/granite/blob/master/docs/imports.md

Did this also override your timestamps?

**Comment by ggtrigg** [comment]
The `import` interface does override any supplied timestamps. I got around it by making a local modification so that the import only sets the timestamps unless both `created_at` & `updated_at` are supplied. vis.
```
model.set_timestamps if (model.updated_at.nil? || model.created_at.nil?)
```
at https://github.com/amberframework/granite/blob/59801deb1a503bfb3d047fdbcea11431690b6d2d/src/adapter/mysql.cr#L68

If it helps I could raise a pull request with this change (and also for the other db adapters)?

**Comment by crimson-knight** [comment]
@ggtrigg this is resolved with the new `skip_timestamps` option that can be passed in
