### ISSUE TITLE
#to_yaml test fails on M1 Mac

### ISSUE THREAD

**Issue by stufro** [amberframework/granite#488]
# System Info
**OS**: Ventura 13.6
**Crystal version**: 1.9.2
**LLVM**: 15.0.7
**Result of `arch` command**: arm64

---

If I pull master and run this test locally - [spec/granite_spec.cr:265](https://github.com/amberframework/granite/blob/5afa787eef71224cdbde6b7d6e894471720caed7/spec/granite_spec.cr:265). I get this error:

```
F..

Failures:

  1) Granite::Base YAML #to_yaml emits nil values when told
     Failure/Error: t.to_yaml.should eq result

       Expected: "---\n" +
       "id:\n" +
       "name: test todo\n" +
       "priority: 20\n" +
       "created_at:\n" +
       "updated_at:\n"
            got: "---\n" +
       "id: \n" +
       "name: test todo\n" +
       "priority: 20\n" +
       "created_at: \n" +
       "updated_at: \n"

     # spec/granite_spec.cr:272

Finished in 62.01 milliseconds
3 examples, 1 failures, 0 errors, 0 pending

Failed examples:

crystal spec spec/granite_spec.cr:265 # Granite::Base YAML #to_yaml emits nil values when told
```

The test itself contains a macro which checks whether the compile-time flag of `:darwin` is set. This makes me think that this has something to do with running on my M1 mac.

I have confirmed this isn't isolated to my machine - @jphaward has also tried this on his M1 and gets the same error.

**Comment by crimson-knight** [comment]
Looks like the test would pass if you added a space in the expected output: `"id: \n"` because that's what it's getting.

Looks like that spacing wasn't consistent in the result, which probably is system dependent on whether or not it cares about the trailing space.

**Comment by crimson-knight** [comment]
Okay I see why the spacing is different, I wasn't paying enough attention at first.

You got the non-darwin response when running on a Mac, so the compile-time flag didn't pick up that you're on an M1.

A few things come to mind:
1. Is this flag worth keeping? @kalinon might know why it's there
2. Are you running the tests in a docker file on your M1?

**Comment by stufro** [comment]
To answer number 2, the failure only occurs when running natively on my M1.

**Comment by kalinon** [comment]
The `darwin` flag is due to the different yaml output from the underlying `yaml` lib. It seems on darwin it does not include a space after an empty value:

```
%(---\nid:\nname: test todo\npriority: 20\ncreated_at:\nupdated_at:\n)
```

while on linux a space is included before the newline:

```
%(---\nid: \nname: test todo\npriority: 20\ncreated_at: \nupdated_at: \n)
```

This may have changed due to apple/brew updating the underlying yaml lib.

**Comment by jphaward** [comment]
@kalinon I asked someone with a non-m1 Mac to test this where their default target values are:
`Default target: x86_64-apple-macosx`

The result they got is the "non-darwin" option however the test still expected the darwin route.

I can't find too much info online about this sadly.

Do you think it's worth removing the darwin conditional to fix this issue and if this issue is raised again a more specific conditional can be added?

**Comment by crimson-knight** [comment]
@jphaward I'd say let's just remove the logic then. It sounds like MacOS and/or the lib Crystal relies on when running on MacOS has probably updated how yml is parsed & made this unnecessary now

**Comment by kalinon** [comment]
@jphaward @crimson-knight yes, i think this can be removed now.
